{ -> docker.image('slave-sbt').inside 
    {
        stage('Build') {
                sh 'sbt compile'
        }
        stage('Test') {
                sh 'sbt test'
        }
        stage('Deploy Locally') {
                sh 'sbt docker:publishLocal'
        }
    }
}
