{ ->
    pipeline {
        agent any

        stages {
            stage('Build') {
                steps {
                    echo 'Building..'
                    shell 'sbt compile'
                }
            }
            stage('Test') {
                steps {
                    echo 'Testing..'
                    shell 'sbt test'
                }
            }
            stage('Deploy Locally') {
                steps {
                    echo 'Deploying....'
                    shell 'sbt docker:publishLocal'       
                }
            }
        }
    }
}
