{ -> docker.image('slave-sbt').inside
    {
        stage('Build') {
                sh 'sbt compile'
        }
        stage('Creating Docker container') {
                sh 'sbt docker:stage'
        }
        stage('Deploy to Heroku') {
                echo 'We will deploy to Heroku, sooner or later ...'
        }
    }

}
